// This file will be auto-generated by openapi-typescript
// Run: npm run generate:api-types
// Placeholder types for development

export interface paths {
  '/api/v1/health': {
    get: {
      responses: {
        200: {
          content: {
            'application/json': {
              status: string;
              version: string;
            };
          };
        };
      };
    };
  };
}

export interface components {
  schemas: {
    // Placeholder schemas - will be replaced by generated types
    Agent: Record<string, unknown>;
    Tool: Record<string, unknown>;
    Workflow: Record<string, unknown>;
    Execution: Record<string, unknown>;
  };
}

export type operations = Record<string, unknown>;
